### ISSUE TITLE
Rimozione server 🦄

### ISSUE THREAD

**Issue by gbonanome** [iorestoacasa-work/iorestoacasa.work#104]
Ciao ragazzi e ancora supercomplimenti per il progetto!!

La mia istanza https://jitsi.unicorni.team/ era stata messa a disposizione grazie all'offerta di 3 mesi gratuiti di una VPS su ShellRent tramite Solidarietà Digitale. Ora i 3 mesi sono finiti quindi dovrò tirare giù il server 😅 
Mi spiace non far più parte di questa bellissima famiglia ma il progetto ha fatto passi enormi negli ultimi mesi e ci sono un sacco di macchine migliori su cui contare.

Apro la issue un po' perchè non sapevo se il server down se ne sarebbe andato via da solo dall'elenco, un po' pechè ho visto che unicorni.team compare [nel codice da qualche parte](https://github.com/iorestoacasa-work/iorestoacasa.work/blob/1332a6a1e9f4eace92f915a11dd5100ad5785f2b/_includes/common_table.html) 😅

**Comment by tapionx** [comment]
Puoi spegnere il server senza problemi: se non arrivano le metriche il server scompare in automatico dalla lista.
Grazie per il tuo prezioso contributo! :smiley:
