### ISSUE TITLE
Cambio password su Grafana

### ISSUE THREAD

**Issue by eppesuig** [iorestoacasa-work/iorestoacasa.work#105]
Ciao,
ho perso la password per l'accesso a https://monitoring.iorestoacasa.work/ e ho cercato di reimpostarla usando il link «Forgot your password?» presente nella parte inferiore della pagina di accesso, ma non ho mai ricevuto l'email (e ho controllato sia la cartella della posta indesiderata, sia i log del server SMTP).

Come posso fare?

Grazie,
Giuseppe

**Comment by tapionx** [comment]
Scrivimi su telegram http://telegram.me/tapion
