### ISSUE TITLE
[NEW SERVER]

### ISSUE THREAD

**Issue by myfoxx** [iorestoacasa-work/iorestoacasa.work#106]
**EDU MEET**

---

**https://galadriel.myfox.ovh/**

---

**https://galadriel.myfox.ovh:8081**

---

**Desidero che venga visualizzato il seguente nome nella sezione dei crediti**

*myfox*

---

**Vorrei che venisse linkato questo link al nome specificato in precedenza**

*https://www.myfox.org*

---

**Tipo di contributo**
* Azienda
* Privato
* Associazione
* Istituzione 

*Privato*

---

**Numero di core messi a disposizione**

* 4*

----

**Quantità di RAM messa a disposizione**

*4GB*

---

**Quantità di banda messa a disposizione**

*1Gbps*

**Comment by Radeox** [comment]
![Screenshot_20201118_100631](https://user-images.githubusercontent.com/9751015/99509386-fd2e6f00-2985-11eb-83b0-59fe1b447bc6.png)
