### ISSUE TITLE
[NEW SERVER]

### ISSUE THREAD

**Issue by maxtoor** [iorestoacasa-work/iorestoacasa.work#109]
**Tipo di software**

*MM*

---

**URL del server**

*https://edumeet.na.icb.cnr.it*

---

**URL e porta sul quale sto esponendo le metriche**

*https://edumeet.na.icb.cnr.it:8081/metrics*

---

**Desidero che venga visualizzato il seguente nome nella sezione dei crediti**

*Consiglio Nazionale delle Ricerche - ICB*

---

**Vorrei che venisse linkato questo link al nome specificato in precedenza**

*https://www.icb.cnr.it*

---

**Tipo di contributo**
* Azienda
* Privato
* Associazione
* Istituzione 

*Istituzione*

---

**Numero di core messi a disposizione**

*8*

----

**Quantità di RAM messa a disposizione**

*8GB*

---

**Quantità di banda messa a disposizione**

*1Gbps*

**Comment by Radeox** [comment]
Aggiunto in lista. Grazie per la disponibilità! 🎉
