### ISSUE TITLE
Configurare Jitsi in italiano

### ISSUE THREAD

**Issue by tapionx** [iorestoacasa-work/iorestoacasa.work#19]
nel nostro repository Docker

**Comment by Radeox** [comment]
Jitsi prende la lingua in ordine:
* querystring
* localestorage
* default (o cerca di capirlo se attivo il servizio)

Ma sembra che non viene rispettato il default impostato (non sono riuscito a farlo in locale)
Si potrebe "forzare" con il querystring se si passa dal portale e questo verra' salvato.
Senno nella issue sotto dicevano di settarlo tramite API ma sembra solo un override dello stesso parametro.

https://github.com/jitsi/jitsi-meet/blob/259066e2c69f74257f85acbda3d05c51d0becc41/react/features/base/i18n/languageDetector.web.js#L15

https://github.com/jitsi/jitsi-meet/issues/3143

**Comment by tapionx** [comment]
@Radeox https://webmeeting.opensolution.it/
questo lo vedo in italiano, ho sistema e browser in inglese

**Comment by gbonanome** [comment]
Avevate già visto questo thread vero? 
https://community.jitsi.org/t/changing-the-default-language/15978/2

**Comment by Radeox** [comment]
Farò una prova! 😄

**Comment by tapionx** [comment]
bravo @Radeox !
