### ISSUE TITLE
sito web, minimale e comunicativo

### ISSUE THREAD

**Issue by tapionx** [iorestoacasa-work/iorestoacasa.work#2]
Sezioni:
* tabella dei server, in primo piano nella landing page
* a cosa serve, come lo uso
* come posso aiutare
* FAQ
* footer con link al canale telegram di supporto, a GitHub e credits

**Comment by tapionx** [comment]
requisiti tecnici:

il sito deve essere minimale e leggero, assolutamente meno di 1 MB.
L'unico JavaScript presente sul sito sarà quello che legge il file "hosts.json" e popola la tabella

**Comment by feroda** [comment]
in alto un `<input>` con il nome della stanza da attivare (e da appendere all'URL cliccato) ce lo mettiamo? ;-)

**Comment by tapionx** [comment]
mi piace! bravo @Azzeccagarbugli 
aggiungerei una pagina "Informazioni" che contiene due card:
1. come lo uso
2. come posso aiutare
