### ISSUE TITLE
Integrare Jekyll per le news?

### ISSUE THREAD

**Issue by feroda** [iorestoacasa-work/iorestoacasa.work#20]
Sarebbe carino poter mettere una sezione news in cui scrivere "Oggi Open Solutions si è aggiunta al progetto", oppure "Oggi SEEWEB si è aggiunto al progetto", oppure... rendere come blogpost direttamente i commit al branch master :-D

**Comment by umbertocerrato** [comment]
Così così...

Non metterei troppa carne a cuocere.
Il sito è bello proprio per la sua semplicità :P 

Poi vi sarebbe la necessità di formare un “team social” per il progetto. E sarebbe comunque un ulteriore impegno. Stavo per suggerire: allora perché non creare un account Twitter? Ma come dicevo, non so se il gioco vale la candela...

Per ora Telegram funziona bene come canale di servizio e comunicazione :) (o almeno questo è ciò che vedo, sono venuto a conoscenza del progetto solo qualche giorno fa)

**Comment by tapionx** [comment]
fatto!
