### ISSUE TITLE
Supporto per caratteri speciali nel nome della stanza

### ISSUE THREAD

**Issue by gbonanome** [iorestoacasa-work/iorestoacasa.work#24]
A quanto pare se si usano caratteri speciali nel nome della stanza il server restituisce un 404.

Esempio: `https://befair1.iorestoacasa.work/una-conferenza`
oppure `https://befair1.iorestoacasa.work/una%20conferenza`

Leggendo le risposte a [questo thread](https://community.jitsi.org/t/jitsi-meet-room-name-doesnt-accept-special-chars/17984/) su meet.jit.si dicono che c'è da impostare una regex lato webserver.

Si può implementare la stessa cosa?

**Comment by feroda** [comment]
@tapionx , questo è nginx per i tuoi denti: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example#L33

**Comment by Azzeccagarbugli** [comment]
Come workaround per il momento si potrebbe pensare di inserire una form-validation nel pannello relativo alla creazione della stanza presente nella homepage

**Comment by tapionx** [comment]
@gbonanome nella nuova versione di Jitsi questo problema è stato risolto!
https://befair1.iorestoacasa.work/una-conferenza
