### ISSUE TITLE
Abilitazione streaming YouTube

### ISSUE THREAD

**Issue by feroda** [iorestoacasa-work/iorestoacasa.work#25]
Installare/attivare Jibri https://github.com/jitsi/jibri, @tapionx prova nell'installazione docker

**Comment by andreus94** [comment]
@tapionx ti stai occupando della installazione di Jibri?

**Comment by tapionx** [comment]
@andreus94 no, ho fatto qualche prova e poi ho abbandonato.
Nel repository docker dovrebbe essere semplice attivarlo.
Se hai tempo, provaci pure! Sarebbe grandioso poi documentare in questa issue la procedura da seguire, e poi integrarla nel repository

**Comment by ivoermejo** [comment]
la butto là...
sapete che OBS-Studio supporta websocket? 
in questo modo, voi veri programmatori,
avendo installato un obs(sotto banco) potreste creare un pannellino con:
chiave diretta YouTube, Rec / pause / stop

**Comment by feroda** [comment]
La issue è risolta nel repository apposito docker-jitsi-meet:

https://github.com/iorestoacasa-work/docker-jitsi-meet/commit/4852414e864e2336f5aa62a172324ae7f62391a1
