### ISSUE TITLE
verificare il comando sed nel repository iorestoacasa_addmetrics

### ISSUE THREAD

**Issue by tapionx** [iorestoacasa-work/iorestoacasa.work#37]
Ci è stato segnalato che il comando `sed` nello script `add-metrics.sh` alla riga 32 non funziona correttamente.
Bisogna verificare ed eventualmente correggerlo.
https://github.com/iorestoacasa-work/iorestoacasa_addmetrics/blob/master/add-metrics.sh#L32

**Comment by feroda** [comment]
https://github.com/iorestoacasa-work/iorestoacasa_addmetrics/commit/d472dd7585ac6fcb77b00f3ca20a4b39da65ccd5#diff-4f414438fba107d83a455b082e6695efR32
