### ISSUE TITLE
inserire nella homepage le istanze pubbliche di MM

### ISSUE THREAD

**Issue by tapionx** [iorestoacasa-work/iorestoacasa.work#40]
Per il momento sono queste (senza metriche):
https://edu.meet.garr.it/
https://edumeet.imaa.cnr.it/

dove le inseriamo? Nella tabella con una pillola "BETA" ?

**Comment by dambro** [comment]
@tapionx questa issue si può chiudere ?

<img width="1056" alt="Schermata 2020-03-27 alle 10 47 05" src="https://user-images.githubusercontent.com/1841629/77743432-5bce6380-7018-11ea-8d71-ed694e04f53d.png">

**Comment by tapionx** [comment]
si! grazie!
