### ISSUE TITLE
scrivere la documentazione in italiano a prova di "utonto" per installare MM tramite docker

### ISSUE THREAD

**Issue by tapionx** [iorestoacasa-work/iorestoacasa.work#49]
replicare quanto già fatto per Jitsi:
https://github.com/iorestoacasa-work/docker-jitsi-meet/blob/master/README.md

Una guida di installazione in italiano, semplice, con procedure da seguire passo passo, ben testate e documentate.

Descrivo qua brevemente i passaggi da documentare per l'installazione.

```
cd /opt/
git clone https://github.com/iorestoacasa-work/mm/
cd mm
```
ottenere dei certificati SSL per il dominio su cui si vuole pubblicare MM
` certbot certonly -d miodominio.it --standalone`

assicurarsi che il dominio risolva correttamente all'IP della macchina

copiare i certificati (chiave pubblica e privata) nella cartella certs/

creare i file di configurazione di MM partendo dai template di esempio:
`cp conturn.example.conf coturn.conf`
ed modificare opportunamente i CHANGEME

`cp configs/app/config.example.js configs/app/config.js`
e modificare opportunamente i CHANGEME

`cp configs/server/config.example.js configs/server/config.js`
e modificare opportunamente i CHANGEME

ora lanciare docker
`docker-compose up -d`

verificare che MM stia funzionando collegandosi con il browser all'hostname scelto e facendo una videochiamata

verificare che le metriche siano esposte:
`curl http://hostname.scelto.it:8081/metrics`

**Comment by wario9k** [comment]
### **Come installare Multiparty Meeting su ubuntu 18.04 (for dummies)**

**Step 1: INSTALLAZIONE DOCKER:**

_ATTENZIONE: non eseguire questo step se sul tuo server è già presente DOCKER, verifica se è presente una versione con il comando:  `docker --version`_

Prima di effettuare l’installazione effettuare l’update

`sudo apt-get update`

Rimuovere eventuali installazioni precedenti di docker.  

 `sudo apt-get remove docker docker-engine docker.io`
 
Proseguire con l’installazione
   
`sudo apt install docker.io`

`sudo systemctl start docker`

`sudo systemctl enable docker`

Verifica la versione appena installata
 `docker --version`

**Step 2: INSTALLAZIONE DOCKER COMPOSE:**

_ATTENZIONE: non eseguire questo step se sul tuo server è già presente DOCKER, verifica se è presente una versione con il comando: `docker-compose -version`_

Prima di effettuare l’installazione effettuare l’update

`sudo apt-get update`

`sudo apt-get upgrade`
    
Verificare se il comando curl è presente, se viene restituito l’errore allora installarlo
`curl`  in caso di errore `sudo apt install curl`

Proseguire nell’installazione
    
`sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

`sudo chmod +x /usr/local/bin/docker-compose`

Verifica la versione appena installata

`docker-compose -version`


**Step 3: INSTALLAZIONE CERTBOT:**
 
Lanciare i seguenti comandi
`sudo apt-get update`

`sudo apt-get install software-properties-common`

`sudo add-apt-repository universe`

`sudo add-apt-repository ppa:certbot/certbot`

`sudo apt-get update`

`sudo apt-get install certbot`

**Step 4: INSTALLAZIONE MULTIPARTY MEET**

Spostarsi nella cartella opt    
`cd /opt/`
    
`git clone https://github.com/iorestoacasa-work/mm/`

Spostarsi nella cartella mm    

`cd mm`

Generare il proprio certificato SSL, sostituendo dai comandi seguenti EXAMPLE.COM con il vostro dominio.

`certbot certonly -d EXAMPLE.COM --standalone`

Quando richiesto inserire la propria email

Copiare i certificati (chiave pubblica e privata) appena creati nella cartella certs/
ATTENZIONE: i certificati dovranno essere spostati all’interno della cartella certs/ alla scadenza con quelli rinnovati

La cartella del certificato farà riferimento al nome del vostro dominio

`cp /etc/letsencrypt/live/EXAMPLE.COM/fullchain.pem certs/`

`cp /etc/letsencrypt/live/EXAMPLE.COM/privkey.pem certs/`


Copiare i file di configurazione di MM partendo dai template di esempio e modificare opportunamente i CHANGEME 

`cp /opt/mm/coturn.example.conf coturn.example.conf` 

user=NOMEUTENTECHEVOGLIAMO:PASSWORDASCELTA
INSERIRE Username e Password che saranno da usare anche nel conf.js

 `nano coturn.conf `

Copiare il file config di esempio e modificare opportunamente i CHANGEME
 `cp configs/app/config.example.js configs/app/config.js `

 `nano configs/app/config.js `

Copiare il file config di esempio e modificare opportunamente i CHANGEME

`cp configs/server/config.example.js configs/server/config.js`

 `nano configs/server/config.js`

ora lanciare docker

`docker-compose up -d`

verificare che MM stia funzionando collegandosi con il browser all'hostname scelto e facendo una videochiamata

verificare che le metriche siano esposte:

`curl http://hostname.scelto.it:8081/metrics`

**Enjoy :-)**

**Comment by tapionx** [comment]
fatto! grazie mille
