### ISSUE TITLE
trovare nuovi server

### ISSUE THREAD

**Issue by tapionx** [iorestoacasa-work/iorestoacasa.work#5]
volontari e attivisti devono capire al volo:

- che possono aggiungere un loro server, gestito da loro, alla tabella

- dove devono contattarci (chat telegram di supporto con link pubblico)

- requisiti minimi?

- esporre le metriche obbligatorio o no?

- è opportuno contattare tutti i provider che hanno datacenter in Italia (e dintorni) per chiedere se mettono a disposizione una macchina per la durata dell'emergenza.
I datacenter italiani sono da preferire, per avere minore latenza e congestionamento.

**Comment by tapionx** [comment]
Ho inviato una email a Keliweb, Seeweb e Panservice.
Non riesco a trovare un indirizzo email per Aruba

**Comment by tapionx** [comment]
seeweb ha accettato l'offerta e messo a disposizione una VPS!

**Comment by gbonanome** [comment]
Ho contattato https://www.shellrent.com/ che erano listati nella pagina solidarietadigitale.agid.gov.it/ e mi danno una VPS anche loro :)

**Comment by tapionx** [comment]
@gbonanome grandioso!
Se c'è bisogno posso occuparmi io dell'installazione.
In ogni caso consiglio di seguire questa procedura, perché è l'unico modo con cui siamo riusciti a far funzionare il sistema di monitoraggio (e di conseguenza mostrare il numero di utenti connessi nella landing page)
https://github.com/iorestoacasa-work/docker-jitsi-meet

**Comment by gbonanome** [comment]
👍 fantastico, sì volentieri appena mi arrivano le credenziali di accesso al server magari te le giro via mail così fai direttamente tu che ci metti di certo meno di me ;)

**Comment by tapionx** [comment]
la macchina offerta da Seeweb è online e visibile in homepage

**Comment by tapionx** [comment]
obiettivo raggiunto! ora ci servono nuovi utenti :D
