### ISSUE TITLE
le singole FAQ devono essere "linkabili"

### ISSUE THREAD

**Issue by tapionx** [iorestoacasa-work/iorestoacasa.work#51]
accanto al nome della FAQ deve esserci il simbolino della catena che posso copiare ed incollare.
Incollando l'URL della singola FAQ l'utente può essere indirizzato (tramite fragment) alla risposta che cerca

**Comment by feroda** [comment]
c'è il simbolino ma manca il fragment ;-) @Azzeccagarbugli !!!!!

**Comment by Azzeccagarbugli** [comment]
@pharmak0n ha risolto la issue con la pull request https://github.com/iorestoacasa-work/iorestoacasa.work/pull/81

Grandissimo!
