### ISSUE TITLE
scaricare i font di google e fornirli dal nostro webserver

### ISSUE THREAD

**Issue by tapionx** [iorestoacasa-work/iorestoacasa.work#52]
assicurarsi che non ci siano problemi di licenze per farlo

**Comment by Azzeccagarbugli** [comment]
> assicurarsi che non ci siano problemi di licenze per farlo

https://developers.google.com/fonts/faq#can_i_use_fonts_from_the_google_fonts_catalog_on_any_page

> scaricare i font di google e fornirli dal nostro webserver

Issue risolta con l'implementazione del commit: https://github.com/iorestoacasa-work/iorestoacasa.work/commit/609680e362d0a31e4fbf2066e5035dffefc2dd65
