### ISSUE TITLE
fornire il CSS di bootstrap minificato

### ISSUE THREAD

**Issue by tapionx** [iorestoacasa-work/iorestoacasa.work#53]
attualmente stiamo fornendo i CSS di boostrap non minificati, sono 300KB.
Bisogna fornire la versione minificata.
Occhio perchè abbiamo modificato il file https://iorestoacasa.work/dist/css/style.min.css
aggiungendo del CSS custom, che quindi va riportato su un foglio di stile extra nuovo.

**Comment by tapionx** [comment]
https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css
questi sono 19KB, i browser dei nostri utenti ringrazieranno

**Comment by toonhello** [comment]
Buonasera,
mi inserisco per offrire una mano.
Come mai usate bootstrap 3.4.1, non sarebbe meglio passare all'ultima 4.4.x?
Ci sono diverse migliorie che risolvono annosi problemi di gestione dei layout (grid basata su flexbox).

Ho dato un'occhiata al css, mi sembra che alcune font utilizzate sia commerciali, forse conviene sostituirle con qualcuna libera.
http://www.losttype.com/font/?name=tofinopro
https://fontlot.com/60381/gilmer-font-family/

**Comment by Azzeccagarbugli** [comment]
Al momento la versione utilizzata di Bootstrap è la` 4.3.1` e con l'inserimento del commit 5c98a63596ed36965b3dc2c51fa13e01649f340b è stato anche inserito il file CSS minificato!
