### ISSUE TITLE
Rivisitazione della homepage

### ISSUE THREAD

**Issue by Azzeccagarbugli** [iorestoacasa-work/iorestoacasa.work#54]
Rendere la homepage più **user-friendly** e spostare di conseguenza la tabella dei server in una pagina dedicata.

Questo dovrebbe rendere il sito web più facile da comprendere per gli utenti visitatori.

**Comment by feroda** [comment]
vedere se si riescono ad inserire le label con i 4 hashtag.

Per ora:
#smartworking #smartlearning #isolatimanonsoli #hopeaftercovid

**Comment by tapionx** [comment]
fatto! bravo @Azzeccagarbugli
