### ISSUE TITLE
Migliorare l'automazione di segnalazione nuovo server

### ISSUE THREAD

**Issue by feroda** [iorestoacasa-work/iorestoacasa.work#66]
Dare un metodo per poter segnalare un nuovo server rel #65 

In chat a volte segnalano dei nuovi server e la criticità che è che se nessuno risponde, l'utente non si sente seguito. Definire o in modo descrittivo o tramite form un metodo per segnalare un nuovo server pronto. 

Mostrare se possibile i tempi attuali di approvazione nuovo server e anche un grafico che mostri che qualche volta l'accettazione è più lenta.

È un progetto portato avanti da volontari. Il livello di servizio è altissimo. Bisogna trasmettere con calma che l'inserimento dei server lo facciamo ogni giorno alle 14:00 . Con questa condivisione non si diminuisce l'aspettativa di intervento istantaneo. 

E con la risoluzione di questa issue si può ottenre una coda di server.

**Comment by tapionx** [comment]
@feroda possiamo chiedere di creare una issue con tutti i dati richiesti, si può creare un template per la issue

**Comment by Azzeccagarbugli** [comment]
Risolto con il commit https://github.com/iorestoacasa-work/iorestoacasa.work/commit/e366d12356415f5bc150fd0a651eac58b241f34a

Ora si può semplicemente compilare la issue e il gioco è fatto!
