### ISSUE TITLE
Homepage - label videochiamata opzionale

### ISSUE THREAD

**Issue by dambro** [iorestoacasa-work/iorestoacasa.work#76]
Chiarirei all'utente in qualche modo che il nome della stanza è opzionale e non un parametro da inserire obbligatoriamente. Lascio qui due mock grafici d'esempio, ovviamente possiamo trovare altre soluzioni più eleganti:

![Schermata 2020-04-14 alle 13 23 16](https://user-images.githubusercontent.com/1841629/79220842-12be4200-7e55-11ea-9bf7-72f50749ceb5.png)
![Schermata 2020-04-14 alle 13 28 14](https://user-images.githubusercontent.com/1841629/79220846-15b93280-7e55-11ea-950f-bdef7b9efff4.png)

**Comment by Azzeccagarbugli** [comment]
Che ne dici di questa soluzione? 

![image](https://user-images.githubusercontent.com/16477661/79227287-f1af1e80-7e5f-11ea-9373-9f04a05e8f41.png)

Credo sia la meno invasiva e la più chiara, in quanto al click dell'utente viene mostrato il `tooltip` con annessa l'info relativa
