### ISSUE TITLE
Inizio videochiamata - "connettiti e condividi!"

### ISSUE THREAD

**Issue by dambro** [iorestoacasa-work/iorestoacasa.work#77]
Toglierei questa schermata per fare andare subito l'utente alla videocall, la trovo ridondante

<img width="1041" alt="Schermata 2020-04-14 alle 14 18 13" src="https://user-images.githubusercontent.com/1841629/79224134-e6a5bf80-7e5a-11ea-949a-4721b4ac646e.png">

**Comment by Azzeccagarbugli** [comment]
Grazie per il feedback.

Personalmente la trovo utile in quante per molte persone, abituate al tasto di share rapido, è più facile e comprensibile capire cosa fare una volta selezionato il software per la videocall. Con un semplice click posso condividere la mia stanza usando il social che preferisco oppure connettermi direttamente e farlo copiano manualmente il link.

In questi giorni mi sono arrivate diverse telefonate da persone _diversamente giovani_ che non capivano, nella precedete homepage, come condividere il link e credo che quindi questo step sia alquanto chiaro e autoesplicativo per loro.

Dimmi cosa ne pensi, e in caso proponi anche una soluzione!

**Comment by dambro** [comment]
Grazie per la pazienza e per avermi spiegato il contesto, ho capito bene l'esigenza di questo target di utenza. Effettivamente da devices come smartphone e tablet è una pagina che può essere utile nei casi che hai citato, mentre da pc penso che perda molto di utilità, oltre al fatto che in questo secondo caso la condivisione via telegram e whatsapp mi sembrano non funzionare.

Provo a farti una proposta: modificare il percorso per gli utenti che usano il sito da pc, di fatto togliendo il terzo step e aprendo direttamente la pagina della videocall una volta fatta la scelta tra pillola MM e pillola Jitsi ?

**Comment by Azzeccagarbugli** [comment]
Perfetto, ora ne parlo col team e vediamo cosa fare.

Grazie mille per la segnalazione comunque!
