### ISSUE TITLE
Adattività del container principale 

### ISSUE THREAD

**Issue by dambro** [iorestoacasa-work/iorestoacasa.work#78]
Inspect element nella home page, alzo la finestra della console e il container principale sparisce senza adattarsi alla pagina:

![Schermata 2020-04-14 alle 14 23 35](https://user-images.githubusercontent.com/1841629/79224742-f2de4c80-7e5b-11ea-87c8-073d9ab29e01.png)

Refresh della pagina , senza toccare altro e il container si adatta:

![Schermata 2020-04-14 alle 14 23 51](https://user-images.githubusercontent.com/1841629/79224832-143f3880-7e5c-11ea-90d0-dcf8ef0f9ad1.png)

Trascino giù , e quindi rimpicciolisco, la console e il container questa volta scende, adattandosi alla pagina correttamente:

![Schermata 2020-04-14 alle 14 23 57](https://user-images.githubusercontent.com/1841629/79224928-3638bb00-7e5c-11ea-97ab-af4d6a1bb674.png)

**Comment by Azzeccagarbugli** [comment]
Questo dipende purtroppo da `Swiper.js` ovvero la libreria JS che abbiamo usato per costruire il carosello principale nella homepage.

Ogni volta che si fa il resize bisognerebbe fare il refresh della pagina in modo tale che lui possa chiamare l'update.

Bisognerebbe risolverlo in qualche modo e con @Radeox abbiamo provato diverse soluzioni ma nessuna delle tante sembrava funzionare correttamente.

Hai idee?

**Comment by tapionx** [comment]
risolto! grazie @dambro
