### ISSUE TITLE
TypeError: $(...).perfectScrollbar is not a function

### ISSUE THREAD

**Issue by dcappellin** [iorestoacasa-work/iorestoacasa.work#80]
Aprendo la pagina con la lista dei server nella console di FF appare `TypeError: $(...).perfectScrollbar is not a function` nel file `custom.min.js`.

La riga incriminata dovrebbe essere la 23

` $('.message-center, .customizer-body, .scrollable, .scroll-sidebar').perfectScrollbar({
    wheelPropagation: !0
  }),`

**Comment by maspasquali** [comment]
Il problema risiede nel nome della funzione, quello corretto è "perfect-scrollbar". Necessita di due include: <link href="min/perfect-scrollbar.min.css" rel="stylesheet"> e <script src="min/perfect-scrollbar.min.js"></script>
[perfect-scrollbar-master.zip](https://github.com/iorestoacasa-work/iorestoacasa.work/files/4476944/perfect-scrollbar-master.zip)

**Comment by maspasquali** [comment]
... <link href="min/perfect-scrollbar.min.css" rel="stylesheet">

**Comment by maspasquali** [comment]
questo è l'include del .css: "<link href="min/perfect-scrollbar.min.css" rel="stylesheet">"

**Comment by maspasquali** [comment]
https://www.jqueryscript.net/other/Tiny-jQuery-Plugin-For-Beautifing-Scollbars-perfect-scrollbar.html

**Comment by Azzeccagarbugli** [comment]
Errore fixato nel commit https://github.com/iorestoacasa-work/iorestoacasa.work/commit/008988706aa880dfabc2aae0720ef385e6af7658. 

Grazie mille per la segnalazione!
