### ISSUE TITLE
FAQ su come bloccare una stanza

### ISSUE THREAD

**Issue by tapionx** [iorestoacasa-work/iorestoacasa.work#82]
Puoi bloccare la stanza sia su Jitsi che su Multiparty-Meeting.
Su Jitsi puoi impostare una password quando gli ospiti desiderati sono entrati, su Multiparty-Meeting invece puoi premere sul lucchetto per bloccare l'accesso

**Comment by Azzeccagarbugli** [comment]
Domanda inserita con il commit 78f7541, yuppi!
