### ISSUE TITLE
videoconference.opensolution.it

### ISSUE THREAD

**Issue by dpal80** [iorestoacasa-work/iorestoacasa.work#83]
**Tipo di software**

*MM*
---

**URL del server**

*https://videoconference.opensolution.it*
---

**URL e porta sul quale sto esponendo le metriche**

*https://videoconference.opensolution.it8081*

---

**Desidero che venga visualizzato il seguente nome nella sezione dei crediti**

*Open Solution Srl*

---

**Vorrei che venisse linkato questo link al nome specificato in precedenza**

*https://www.opensolution.it*

---

**Tipo di contributo**
* Azienda

---

**Numero di core messi a disposizione**

*2*

----

**Quantità di RAM messa a disposizione**

*8GB*

---

**Quantità di banda messa a disposizione**

*100Mbps*

**Comment by tapionx** [comment]
server aggiunto!
