### ISSUE TITLE
mm.listaimmobiliare.it

### ISSUE THREAD

**Issue by lucacalcaterra** [iorestoacasa-work/iorestoacasa.work#92]
**Tipo di software**

*MM*

---

**URL del server**

*https://mm.listaimmobiliare.it*

---

**URL e porta sul quale sto esponendo le metriche**

*http://mm.listaimmobiliare.it:8081*

---

**Desidero che venga visualizzato il seguente nome nella sezione dei crediti**

*listaimmobiliare.it*

---

**Vorrei che venisse linkato questo link al nome specificato in precedenza**

*https://listaimmobiliare.it*

---

**Tipo di contributo**
* Azienda
---

**Numero di core messi a disposizione**

*4*

----

**Quantità di RAM messa a disposizione**

*8GB*

---

**Quantità di banda messa a disposizione**

*200Mps*

**Comment by tapionx** [comment]
grazie per il contributo @lucacalcaterra !
inseriremo il server prima possibile

**Comment by lucacalcaterra** [comment]
Grazie a voi per l'iniziativa !!

**Comment by Radeox** [comment]
Fatto da @kovoandrey
